-- ════════════════════════════════════════════════════════════════════
-- Feedbacks (avaliação 1‑5) + progresso de apostilas
-- ════════════════════════════════════════════════════════════════════

-- ─── public.feedbacks ───────────────────────────────────────────────
create table if not exists public.feedbacks (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  tipo         text not null check (tipo in ('aula','apostila')),
  aula_id      bigint references public.aulas(id)      on delete cascade,
  apostila_id  bigint references public.apostilas(id)  on delete cascade,
  nota         smallint not null check (nota between 1 and 5),
  categoria    text not null default 'outro'
               check (categoria in ('elogio','sugestao','reclamacao','outro')),
  comentario   text,
  criado_em    timestamptz not null default now()
);

-- Cada usuário avalia cada conteúdo no máximo 1 vez
create unique index if not exists feedbacks_unique_aula     on public.feedbacks (user_id, aula_id)
  where aula_id is not null;
create unique index if not exists feedbacks_unique_apostila on public.feedbacks (user_id, apostila_id)
  where apostila_id is not null;

create index if not exists feedbacks_tipo_idx on public.feedbacks (tipo, criado_em desc);

-- Garante consistência: aula_id obrigatório se tipo='aula', idem apostila
alter table public.feedbacks
  drop constraint if exists feedbacks_tipo_id_consistente,
  add  constraint feedbacks_tipo_id_consistente check (
    (tipo = 'aula'     and aula_id     is not null and apostila_id is null) or
    (tipo = 'apostila' and apostila_id is not null and aula_id     is null)
  );

alter table public.feedbacks enable row level security;

drop policy if exists fb_self_select  on public.feedbacks;
drop policy if exists fb_self_insert  on public.feedbacks;
drop policy if exists fb_self_update  on public.feedbacks;
drop policy if exists fb_self_delete  on public.feedbacks;
drop policy if exists fb_admin_select on public.feedbacks;

create policy fb_self_select on public.feedbacks
  for select to authenticated using (auth.uid() = user_id);
create policy fb_admin_select on public.feedbacks
  for select to authenticated using (public.is_admin());
create policy fb_self_insert on public.feedbacks
  for insert to authenticated with check (auth.uid() = user_id);
create policy fb_self_update on public.feedbacks
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy fb_self_delete on public.feedbacks
  for delete to authenticated using (auth.uid() = user_id or public.is_admin());

-- ─── public.progresso_apostilas ─────────────────────────────────────
create table if not exists public.progresso_apostilas (
  user_id       uuid    not null references auth.users(id)       on delete cascade,
  apostila_id   bigint  not null references public.apostilas(id) on delete cascade,
  segundos      integer not null default 0,
  concluida     boolean not null default false,
  atualizado_em timestamptz not null default now(),
  primary key (user_id, apostila_id)
);

create index if not exists prog_apostilas_user_idx on public.progresso_apostilas (user_id, atualizado_em desc);

alter table public.progresso_apostilas enable row level security;

drop policy if exists prog_ap_self_select on public.progresso_apostilas;
drop policy if exists prog_ap_self_insert on public.progresso_apostilas;
drop policy if exists prog_ap_self_update on public.progresso_apostilas;
drop policy if exists prog_ap_self_delete on public.progresso_apostilas;

create policy prog_ap_self_select on public.progresso_apostilas
  for select to authenticated using (auth.uid() = user_id);
create policy prog_ap_self_insert on public.progresso_apostilas
  for insert to authenticated with check (auth.uid() = user_id);
create policy prog_ap_self_update on public.progresso_apostilas
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy prog_ap_self_delete on public.progresso_apostilas
  for delete to authenticated using (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════════════
-- RPC: admin_list_feedbacks() — junta feedback + autor + título do conteúdo
-- ════════════════════════════════════════════════════════════════════
create or replace function public.admin_list_feedbacks()
returns table (
  id                bigint,
  criado_em         timestamptz,
  user_id           uuid,
  autor_nome        text,
  autor_email       text,
  autor_avatar      text,
  tipo              text,
  conteudo_id       bigint,
  conteudo_titulo   text,
  conteudo_num      text,
  nota              smallint,
  categoria         text,
  comentario        text
)
language sql
security definer
set search_path = public, auth
as $$
  select
    f.id,
    f.criado_em,
    f.user_id,
    p.nome                                                  as autor_nome,
    coalesce(p.email, u.email)::text                        as autor_email,
    p.avatar_url                                            as autor_avatar,
    f.tipo,
    coalesce(f.aula_id, f.apostila_id)                      as conteudo_id,
    case when f.tipo = 'aula'
         then (select a.titulo from public.aulas a where a.id = f.aula_id)
         else (select x.titulo from public.apostilas x where x.id = f.apostila_id)
    end                                                     as conteudo_titulo,
    case when f.tipo = 'aula'
         then (select a.num from public.aulas a where a.id = f.aula_id)
         else (select x.num from public.apostilas x where x.id = f.apostila_id)
    end                                                     as conteudo_num,
    f.nota,
    f.categoria,
    f.comentario
  from public.feedbacks f
  join public.perfis    p on p.id = f.user_id
  join auth.users       u on u.id = f.user_id
  where public.is_admin()
  order by f.criado_em desc;
$$;

revoke all on function public.admin_list_feedbacks() from public, anon;
grant execute on function public.admin_list_feedbacks() to authenticated;
