-- ════════════════════════════════════════════════════════════════════
-- Fórum + Tire sua dúvida
-- Duas áreas (`area`) compartilham as mesmas tabelas:
--   - 'forum'   → debates / chats / discussões abertas
--   - 'duvidas' → perguntas (com botão "marcar resposta como solução")
-- ════════════════════════════════════════════════════════════════════

-- ─── public.forum_topicos ───────────────────────────────────────────
create table if not exists public.forum_topicos (
  id                     bigint generated by default as identity primary key,
  user_id                uuid not null references auth.users(id) on delete cascade,
  area                   text not null check (area in ('forum','duvidas')),
  titulo                 text not null,
  texto                  text,
  fixado                 boolean not null default false,
  fechado                boolean not null default false,
  resolvido_resposta_id  bigint,
  criado_em              timestamptz not null default now(),
  atualizado_em          timestamptz not null default now()
);

create index if not exists topicos_area_idx       on public.forum_topicos (area, criado_em desc);
create index if not exists topicos_user_idx       on public.forum_topicos (user_id);

-- ─── public.forum_respostas ─────────────────────────────────────────
create table if not exists public.forum_respostas (
  id          bigint generated by default as identity primary key,
  topico_id   bigint not null references public.forum_topicos(id) on delete cascade,
  user_id     uuid   not null references auth.users(id) on delete cascade,
  texto       text   not null,
  criado_em   timestamptz not null default now()
);

create index if not exists respostas_topico_idx on public.forum_respostas (topico_id, criado_em);

-- FK tardia para a resposta marcada como solução (depois que respostas existem)
alter table public.forum_topicos
  drop constraint if exists forum_topicos_resolvido_resposta_fk;
alter table public.forum_topicos
  add  constraint forum_topicos_resolvido_resposta_fk
    foreign key (resolvido_resposta_id) references public.forum_respostas(id) on delete set null;

-- Atualiza atualizado_em do tópico quando entra uma nova resposta
create or replace function public.forum_bump_topico()
returns trigger language plpgsql as $$
begin
  update public.forum_topicos set atualizado_em = now() where id = new.topico_id;
  return new;
end $$;
drop trigger if exists forum_respostas_bump_topico on public.forum_respostas;
create trigger forum_respostas_bump_topico
  after insert on public.forum_respostas
  for each row execute function public.forum_bump_topico();

-- ════════════════════════════════════════════════════════════════════
-- RLS
-- ════════════════════════════════════════════════════════════════════
alter table public.forum_topicos   enable row level security;
alter table public.forum_respostas enable row level security;

drop policy if exists topicos_select_all   on public.forum_topicos;
drop policy if exists topicos_insert_self  on public.forum_topicos;
drop policy if exists topicos_update_self  on public.forum_topicos;
drop policy if exists topicos_delete_self  on public.forum_topicos;

create policy topicos_select_all on public.forum_topicos
  for select to authenticated using (true);
create policy topicos_insert_self on public.forum_topicos
  for insert to authenticated with check (auth.uid() = user_id);
-- Autor edita seu tópico; admin pode editar qualquer (e gerencia fixado/fechado/resolvido)
create policy topicos_update_self on public.forum_topicos
  for update to authenticated
  using  (auth.uid() = user_id or public.is_admin())
  with check (auth.uid() = user_id or public.is_admin());
create policy topicos_delete_self on public.forum_topicos
  for delete to authenticated
  using (auth.uid() = user_id or public.is_admin());

drop policy if exists respostas_select_all  on public.forum_respostas;
drop policy if exists respostas_insert_self on public.forum_respostas;
drop policy if exists respostas_update_self on public.forum_respostas;
drop policy if exists respostas_delete_self on public.forum_respostas;

create policy respostas_select_all on public.forum_respostas
  for select to authenticated using (true);
create policy respostas_insert_self on public.forum_respostas
  for insert to authenticated with check (auth.uid() = user_id);
create policy respostas_update_self on public.forum_respostas
  for update to authenticated
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);
create policy respostas_delete_self on public.forum_respostas
  for delete to authenticated
  using (auth.uid() = user_id or public.is_admin());

-- ════════════════════════════════════════════════════════════════════
-- Views — juntam autor (nome/avatar/role) + agregados
-- ════════════════════════════════════════════════════════════════════
create or replace view public.forum_topicos_view as
  select
    t.id,
    t.user_id,
    t.area,
    t.titulo,
    t.texto,
    t.fixado,
    t.fechado,
    t.resolvido_resposta_id,
    t.criado_em,
    t.atualizado_em,
    p.nome        as autor_nome,
    p.avatar_url  as autor_avatar,
    p.role        as autor_role,
    coalesce((select count(*) from public.forum_respostas r where r.topico_id = t.id), 0) as respostas_count,
    greatest(
      t.atualizado_em,
      coalesce((select max(criado_em) from public.forum_respostas r where r.topico_id = t.id), t.atualizado_em)
    ) as ultima_atividade
  from public.forum_topicos t
  join public.perfis p on p.id = t.user_id;

grant select on public.forum_topicos_view to authenticated;

create or replace view public.forum_respostas_view as
  select
    r.id,
    r.topico_id,
    r.user_id,
    r.texto,
    r.criado_em,
    p.nome        as autor_nome,
    p.avatar_url  as autor_avatar,
    p.role        as autor_role
  from public.forum_respostas r
  join public.perfis p on p.id = r.user_id;

grant select on public.forum_respostas_view to authenticated;
