-- ════════════════════════════════════════════════════════════════════
-- Tabelas de engajamento (progresso, notas, comentários) + RPCs LGPD
-- ════════════════════════════════════════════════════════════════════

-- ─── public.progresso_aulas ─────────────────────────────────────────
create table if not exists public.progresso_aulas (
  user_id        uuid not null references auth.users(id) on delete cascade,
  aula_id        bigint not null references public.aulas(id) on delete cascade,
  segundos       integer not null default 0,
  duracao        integer not null default 0,
  concluida      boolean not null default false,
  atualizado_em  timestamptz not null default now(),
  primary key (user_id, aula_id)
);

create index if not exists progresso_user_idx     on public.progresso_aulas (user_id, atualizado_em desc);
create index if not exists progresso_concluida_idx on public.progresso_aulas (user_id, concluida);

alter table public.progresso_aulas enable row level security;

drop policy if exists progresso_self_select on public.progresso_aulas;
drop policy if exists progresso_self_insert on public.progresso_aulas;
drop policy if exists progresso_self_update on public.progresso_aulas;
drop policy if exists progresso_self_delete on public.progresso_aulas;

create policy progresso_self_select on public.progresso_aulas
  for select to authenticated using (auth.uid() = user_id);
create policy progresso_self_insert on public.progresso_aulas
  for insert to authenticated with check (auth.uid() = user_id);
create policy progresso_self_update on public.progresso_aulas
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy progresso_self_delete on public.progresso_aulas
  for delete to authenticated using (auth.uid() = user_id);

-- ─── public.notas_aulas ─────────────────────────────────────────────
create table if not exists public.notas_aulas (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  aula_id     bigint not null references public.aulas(id) on delete cascade,
  segundo     integer not null default 0,
  texto       text not null,
  criado_em   timestamptz not null default now()
);

create index if not exists notas_user_aula_idx on public.notas_aulas (user_id, aula_id, segundo);

alter table public.notas_aulas enable row level security;

drop policy if exists notas_self_select on public.notas_aulas;
drop policy if exists notas_self_insert on public.notas_aulas;
drop policy if exists notas_self_update on public.notas_aulas;
drop policy if exists notas_self_delete on public.notas_aulas;

create policy notas_self_select on public.notas_aulas
  for select to authenticated using (auth.uid() = user_id);
create policy notas_self_insert on public.notas_aulas
  for insert to authenticated with check (auth.uid() = user_id);
create policy notas_self_update on public.notas_aulas
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy notas_self_delete on public.notas_aulas
  for delete to authenticated using (auth.uid() = user_id);

-- ─── public.comentarios_aulas ───────────────────────────────────────
create table if not exists public.comentarios_aulas (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  aula_id     bigint not null references public.aulas(id) on delete cascade,
  parent_id   bigint references public.comentarios_aulas(id) on delete cascade,
  texto       text not null,
  criado_em   timestamptz not null default now()
);

create index if not exists com_aula_idx   on public.comentarios_aulas (aula_id, criado_em);
create index if not exists com_parent_idx on public.comentarios_aulas (parent_id);

alter table public.comentarios_aulas enable row level security;

drop policy if exists com_select_all     on public.comentarios_aulas;
drop policy if exists com_insert_self    on public.comentarios_aulas;
drop policy if exists com_update_self    on public.comentarios_aulas;
drop policy if exists com_delete_self    on public.comentarios_aulas;
drop policy if exists com_delete_admin   on public.comentarios_aulas;

-- Qualquer autenticado vê os comentários de aulas que tem acesso
create policy com_select_all on public.comentarios_aulas
  for select to authenticated
  using (
    exists (
      select 1 from public.aulas a
      where a.id = aula_id
        and (a.disponivel = true or public.is_admin())
    )
  );

create policy com_insert_self on public.comentarios_aulas
  for insert to authenticated
  with check (auth.uid() = user_id);

create policy com_update_self on public.comentarios_aulas
  for update to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- O dono apaga o próprio; admin apaga qualquer.
create policy com_delete_self on public.comentarios_aulas
  for delete to authenticated
  using (auth.uid() = user_id or public.is_admin());

-- View pública que junta comentário + nome/avatar do autor
create or replace view public.comentarios_aulas_view as
  select
    c.id, c.aula_id, c.parent_id, c.texto, c.criado_em, c.user_id,
    p.nome    as autor_nome,
    p.avatar_url as autor_avatar,
    p.role    as autor_role
  from public.comentarios_aulas c
  join public.perfis p on p.id = c.user_id;

grant select on public.comentarios_aulas_view to authenticated;

-- ════════════════════════════════════════════════════════════════════
-- RPCs de LGPD
-- ════════════════════════════════════════════════════════════════════

-- Retorna um JSON com TODOS os dados do usuário (perfil + progresso + notas + comentários)
create or replace function public.export_my_data()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  uid uuid := auth.uid();
  result jsonb;
begin
  if uid is null then
    raise exception 'Usuário não autenticado';
  end if;

  select jsonb_build_object(
    'exportado_em', now(),
    'perfil',      (select to_jsonb(p.*) from public.perfis p where p.id = uid),
    'auth',        (select jsonb_build_object('email', u.email, 'criado_em', u.created_at, 'ultimo_login', u.last_sign_in_at) from auth.users u where u.id = uid),
    'progresso',   coalesce((select jsonb_agg(to_jsonb(x.*)) from public.progresso_aulas x where x.user_id = uid), '[]'::jsonb),
    'notas',       coalesce((select jsonb_agg(to_jsonb(x.*)) from public.notas_aulas       x where x.user_id = uid), '[]'::jsonb),
    'comentarios', coalesce((select jsonb_agg(to_jsonb(x.*)) from public.comentarios_aulas x where x.user_id = uid), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on function public.export_my_data() from public, anon;
grant execute on function public.export_my_data() to authenticated;

-- Deleta a conta do usuário autenticado (e dados em cascata via FK)
create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'Usuário não autenticado';
  end if;

  -- delete em auth.users → cascata via FK em perfis, progresso, notas, comentarios
  delete from auth.users where id = uid;
end;
$$;

revoke all on function public.delete_my_account() from public, anon;
grant execute on function public.delete_my_account() to authenticated;
