-- ════════════════════════════════════════════════════════════════════
-- Tabela: public.aulas
-- Armazena as videoaulas exibidas no menu "Aulas" do dashboard.
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.aulas (
  id           bigint generated by default as identity primary key,
  num          text,
  titulo       text not null,
  descricao    text,
  video_url    text,                              -- URL padrão (qualidade default)
  qualidades   jsonb not null default '[]'::jsonb, -- [{ "label":"1080p", "url":"..." }, ...]
  thumb_url    text,
  ordem        integer not null default 0,
  disponivel   boolean not null default false,
  criado_em    timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists aulas_ordem_idx      on public.aulas (ordem);
create index if not exists aulas_disponivel_idx on public.aulas (disponivel);

-- Trigger para atualizar `atualizado_em`
create or replace function public.aulas_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.atualizado_em := now();
  return new;
end;
$$;

drop trigger if exists aulas_set_updated_at on public.aulas;
create trigger aulas_set_updated_at
  before update on public.aulas
  for each row execute function public.aulas_set_updated_at();

-- ════════════════════════════════════════════════════════════════════
-- RLS — Row Level Security
-- - Usuários autenticados podem LER aulas disponíveis.
-- - Admins (perfis.role = 'admin') podem ler todas e fazer INSERT/UPDATE/DELETE.
-- ════════════════════════════════════════════════════════════════════
alter table public.aulas enable row level security;

-- Helper: é admin?
create or replace function public.is_admin()
returns boolean language sql security definer stable as $$
  select exists (
    select 1 from public.perfis p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

-- SELECT: usuário comum vê só disponíveis; admin vê tudo
drop policy if exists aulas_select_user  on public.aulas;
drop policy if exists aulas_select_admin on public.aulas;

create policy aulas_select_user on public.aulas
  for select to authenticated
  using (disponivel = true or public.is_admin());

-- INSERT / UPDATE / DELETE: apenas admin
drop policy if exists aulas_insert_admin on public.aulas;
drop policy if exists aulas_update_admin on public.aulas;
drop policy if exists aulas_delete_admin on public.aulas;

create policy aulas_insert_admin on public.aulas
  for insert to authenticated
  with check (public.is_admin());

create policy aulas_update_admin on public.aulas
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy aulas_delete_admin on public.aulas
  for delete to authenticated
  using (public.is_admin());

-- ════════════════════════════════════════════════════════════════════
-- (Opcional) Bucket público de vídeos no Storage
-- Execute no Supabase Dashboard → Storage caso queira hospedar os MP4
-- diretamente no Supabase:
--
--   1. Criar bucket "aulas-videos" (Public)
--   2. Policies: SELECT público; INSERT/UPDATE/DELETE apenas admin
--
-- Exemplo de policy admin para o bucket:
--
--   create policy "aulas_videos_admin_write" on storage.objects
--     for all to authenticated
--     using  (bucket_id = 'aulas-videos' and public.is_admin())
--     with check (bucket_id = 'aulas-videos' and public.is_admin());
-- ════════════════════════════════════════════════════════════════════
